.TH "OPENFETION" 1 "2010-12-26" "" ""
.SH NAME
openfetion \- open source implementation of fetion protocol client
.SH SYNOPSIS
.B openfetion
\-f SOURCE \-t DEST \-d MESSAGE
.br
.B openfetion
\-f SOURCE \-m \-d MESSAGE
.br
.B openfetion
\-f SOURCE \-p \-t DEST \-d MESSAGE
.br
.B openfetion
\-f SOURCE \-g NUM
.br
.SH DESCRIPTION
.PP
openfetion is a fetion client for Linux based on GTK+2.0, using Fetion  
Protocol Version 4.
.PP
It supports most useful functions of China Mobile Fetion, more important, it's small and fast, and is better in look.
.TP
\fB\-f\fR 
specify which number you will use to send a message
.TP
\fB\-t\fR
specify which number you will send a message to
.TP
\fB\-d\fR
message you will send
.TP
\fB\-m\fR
send a message to myself
.TP
\fB\-p\fR
send a message to the phone
.TP
\fB\-g\fR
get information of specific mobile number
.TP
\fB\-h\fR, \fB\-H\fR
display this help and exit

.SH EXAMPLES
.PP
send "hello world" to 18788888888:
.TP
openfetion \-f 15288888888 \-t 1878888888 \-d "hello world"
.PP
send "hello world" to yourself:
.TP
openfetion \-m \-f 15288888888 \-d "hello world"
.PP
get information of 18788888888:
.TP
openfetion \-f 15288888888 \-g 1878888888

.SH AUTHOR
Written by Aron Xu <happyaron.xu@gmail.com>.
.RE
.PP

.SH RESOURCES
openfetion home page: http://code.google.com/p/ofetion
.RE
.PP

.SH COPYING
Copyright \(co 2009 Aron Xu.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.PP
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.PP
